import{a as T,S,i as n}from"./assets/vendor-f736e62a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const H="42710952-cb07850fe6c5f6774b64d780f",q="https://pixabay.com/api/";async function L(o,e,s){try{return(await T.get(q,{params:{key:H,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const d=document.querySelector(".gallery"),b=new S(".gallery a",{captionsData:"alt",captionDelay:250});b.refresh();function w(o){o.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;d.insertAdjacentHTML("beforeend",s)}),b.refresh()}const f=document.querySelector(".scroll-to-top"),P=document.querySelector(".form"),g=document.querySelector(".search-input"),E=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");y();let c="",l=1;const p=15;P.addEventListener("submit",$);async function $(o){if(o.preventDefault(),c=g.value.trim(),l=1,d.innerHTML="",c===""){n.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),a();return}v();try{const e=await L(c,l,p),s=e.totalHits;if(e.hits.length===0){d.innerHTML="",n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),a();return}else w(e.hits),g.value="",m();p*l>=s?(n.success({title:"Success",color:"green",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a()):m()}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{y()}}u.addEventListener("click",async()=>{try{u&&(l+=1);const o=await L(c,l,p),e=o.totalHits;w(o.hits),v(),p*l>=e?(n.success({title:"Success",color:"green",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a()):m();const s=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(o){n.error({title:"Error",message:`Error fetching more images: ${o}`})}finally{y()}});function v(){E.classList.remove("hidden")}function y(){E.classList.add("hidden")}function m(){u.style.display="block"}function a(){u.style.display="none"}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?f.style.display="flex":f.style.display="none"});function C(){window.scrollTo({top:0,behavior:"smooth"})}f.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
